name: ballistic
description: Calculation of the bullet trajectory in flight, bullet drop, bullet path, bullet velocity, wind deflection, and terminal velocity in a 2D environment. |
version: 1.0.1
repository: https://github.com/deicon/ballistic

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  matcher: ^0.12.10

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
